version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdoc-to-markdown
    versions:
    - 6.0.1
    - 7.0.0
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: eslint-config-xo
    versions:
    - 0.34.0
    - 0.35.0
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: eslint-plugin-ava
    versions:
    - 11.0.0
